<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JTNN1PTL" ignored="0" name="Validating title in the page" tests="1" failures="0" timestamp="2020-09-17T09:19:51 EDT" time="0.084" errors="0">
  <testcase name="@BeforeTest initialize" time="0.018" classname="Academy.ValidateTitle">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Resources.Base.initilizeDriver(Base.java:45)
at Academy.ValidateTitle.initialize(ValidateTitle.java:25)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest initialize -->
  <testcase name="@AfterTest tearDown" time="-1.600348791494E9" classname="Academy.ValidateTitle">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.002" classname="Academy.HomePage">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Academy.HomePage.tearDown(HomePage.java:55)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="validateAppTitle" time="0.0" classname="Academy.ValidateTitle">
    <skipped/>
  </testcase> <!-- validateAppTitle -->
</testsuite> <!-- Validating title in the page -->
